name: Build Plugin and Create Release
on:
  push:
    branches:
      - master

env:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build plugin
        run: ./gradlew build

      - name: Archive plugin
        run: zip -r plugin.zip <path_to_plugin_files>

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: plugin.zip

      - name: Attach plugin artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./plugin.zip
          asset_name: plugin.zip
          asset_content_type: application/zip
